### PR TITLE
Conflict with Studio autocomplete

### PR DESCRIPTION
**Pull request by falkolab**
It intercepts with Studio autocomplete when press on `_` and then `.` as result you got: _updateMessage.

### CODE REVIEW

**Comment by FokkeZB** [comment]
Huh? Could you explain a bit more?

**Comment by falkolab** [comment]
Try to open project in Studio with your widget installed. Then press _ and . (point) and you will see.

**Comment by falkolab** [comment]
Studio applies automatically "_updateMessage." instead "_."

**Comment by FokkeZB** [comment]
Sorry, I rather have Studio fixed then workaround with the widget:
https://jira.appcelerator.org/browse/TISTUD-8002

**Pull request closed without merging**
