### PR TITLE
added hide and show methods to the widget

### PR DESCRIPTION
**Pull request by Topener**
The ability to hide and show the IS controller is very useful in certain cases.

### CODE REVIEW

**Comment by FokkeZB** [comment]
Could you update the test-app in the test-branch to demonstrate the use? :stuck_out_tongue_winking_eye:

**Comment by Topener** [comment]
you want me to create another pull request for that? :)

**Comment by FokkeZB** [comment]
Uh.. yes, I guess that's only way indeed.

**Comment by Topener** [comment]
hmm it is hard to think of a use case in the test app as that is very limited. I use it in combination with your `pull-to-refresh` widget. And when refreshing, I reset the collection and refetch it. At that point, I want to hide the `IS` view

**Pull request merged**
